"""обавлено поле store в Cashier

Revision ID: aadc39958d77
Revises: edea0f6dbe73
Create Date: 2025-02-20 00:50:19.584872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadc39958d77'
down_revision = 'edea0f6dbe73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashier', schema=None) as batch_op:
        batch_op.drop_column('store')

    # ### end Alembic commands ###
