"""Add debtor columns to CashierReport

Revision ID: edea0f6dbe73
Revises: 
Create Date: 2025-02-17 19:41:01.750076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edea0f6dbe73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashier_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debtor_names', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('debtor_amounts', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashier_report', schema=None) as batch_op:
        batch_op.drop_column('debtor_amounts')
        batch_op.drop_column('debtor_names')

    # ### end Alembic commands ###
